### ISSUE TITLE
The noflo.js customiser for the browser crashes

### ISSUE THREAD

**Issue by th0br0** [noflo/noflo#288] opened 2015-06-05 12:52 UTC
Regardless of the configuration options, the Heroku app seems to crash.

http://noflojs.org/download/

**Comment by jonnor** [comment] 2015-11-10 15:58
Yes, it has been broken since forever. Install noflo and component libs using NPM/component.io

**Comment by jonnor** [comment] 2015-11-10 15:58
Here is a helper grunt task: https://github.com/noflo/grunt-noflo-browser

**Comment by bergie** [comment] 2016-01-23 21:22
Duplicate of #175

**Closed by bergie** 2016-01-23 21:22 UTC
