### ISSUE TITLE
Download for noflo browser version not working

### ISSUE THREAD

**Issue by Gytaco** [noflo/noflo#277] opened 2015-02-20 05:32 UTC
The current link and options do not allow you to download the prebuilt script.

http://noflojs.org/download/

Error below

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by bergie** [comment] 2015-02-20 14:59
Good point. I think in general we should retire that interface and instead focus on providing NoFlo to browsers via component.io (already works well) and NPM/browserify

**Comment by Gytaco** [comment] 2015-02-26 00:26
I haven't seen any info on the component.io option? How far is the browserify version from being stable??

**Comment by jonnor** [comment] 2015-03-26 11:43
Browserify is experimental, will be that way until someone gives it another couple of days of dedicated time.

**Comment by bergie** [comment] 2015-04-18 23:50
Duplicate of #175

**Closed by bergie** 2015-04-18 23:50 UTC
